[package]
name = "gameoflife-rs"
version = "0.1.0"
authors = ["Thomas Koster"]
edition = "2018"

[profile.release]
opt-level = 3

[dependencies]
sdl2 = "0.34.3"

[dev-dependencies]
criterion = "0.3"

[lib]
name = "gameoflife"
path = "src/game.rs"

[[bench]]
name = "game-bench"
harness = false
